[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["John Sutherland <john@starstock.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2"
png = "0.16.1"